version: '3.9'

services:

  backend:
    build:
      context: .
      dockerfile: docker/build/Dockerfile
      target: runner-image
      args:
        - DEBUG=true
        - PG_USER=postgres
        - PG_PASSWORD=django
        - PG_NAME=postgres
        - PG_HOST=db
        - PG_PORT=5432
    platform: linux/amd64
    tty: true
    volumes:
      - /src/backend/market:/src/backend/market
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mail
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/var/lib/redis/data/

  db:
    image: postgres:12.18-alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=django

  backend-worker:
    build:
      context: .
      dockerfile: docker/build/Dockerfile
    platform: linux/amd64
    command: celery worker --app=website
    volumes:
      - /src :/home/backend/src

    environment:
      - BROKER_URL='redis://redis:6379'
      - CELERY_RESULT_BACKEND='redis://redis:6379'
      - CELERY_ACCEPT_CONTENT='application/json'
      - CELERY_TASK_SERIALIZER='json'
      - CELERY_RESULT_SERIALIZER='json'

    depends_on:
      - backend
      - redis

#  dashboard:
#    build:
#      context: .
#      dockerfile: docker/build/Dockerfile
#    command: flower -A website --port=5555 --broker=redis://redis:6379
#    ports:
#      - 5555:5555
#    depends_on:
#      - backend
#      - redis
#      - backend-worker

  mail:
    image: inbucket/inbucket

volumes:
  postgres_data:
  redis_data: